### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by GrbavaCigla** [JordanKnott/project-citadel#1]
```
error Couldn't find a package.json file in "~/project-citadel"
Error: running "yarn build --cwd frontend" failed with exit code 1
exit status 1
```

**Comment by escargot-sans-gluten** [comment]
I have the same problem on Kubuntu 20.04.

**Comment by JordanKnott** [comment]
This is now fixed in the [latest commit](https://github.com/JordanKnott/project-citadel/commit/de03fd9ef7fb3a54adcc7e307b37c3cb447260f4)

Thanks for letting me know of the issue!
