### ISSUE TITLE
Hardcoded addresses

### ISSUE THREAD

**Issue by tionis** [JordanKnott/project-citadel#14]
A few locations in the frontend code contain hardcoded calls to the backend (eg. a post call to http://localhost:3333/users/me/avatar in the profile page template)

**Comment by tionis** [comment]
On another note I would much appreciate an Contributing File specifying how best to contribute to the project.

**Comment by JordanKnott** [comment]
Thanks for letting me know of some that I missed!

They have been updated as of commit [56a8753](https://github.com/JordanKnott/project-citadel/commit/56a8753b923b5eca8f71c879d7827b3e051436a4)

A contributing file is a nice idea, I'll work on adding one!
