### ISSUE TITLE
Feature Request: Meta boards/Cards as boards

### ISSUE THREAD

**Issue by tionis** [JordanKnott/project-citadel#19]
Allow cards to link to another board, so that you can have one big board containing many little ones.    
This would allow for example have one big project board which tracks tinier boards in its own boards.

**Comment by JordanKnott** [comment]
I currently I have a feature planned that will let you create a specific view for a quick overview of selected projects (the feature is called portfolios unless I think of a better name) which sounds like it would accomplish pretty much the same thing as what you're talking about. 

Am I wrong in thinking this, and if so could you explain the use case you had in mind?

**Comment by tionis** [comment]
This would limit the linking to only one time, but is probably a better solution.

For very complex linking simply attaching the board link to the card would be enough. Maybe adding a bit of metadata in the card UI when the url is a board would be doable. (This would be an awesome feature in connection with other link types like youtube video thumbnail embedding or something like that)

**Comment by JordanKnott** [comment]
Hmm, an interesting idea - however I'm going to go ahead and close this until I at least get the portfolios feature done - I think if I get that functionality working the way I intend it will work pretty similar to what you have in mind.

However being able to embed youtube videos in tasks sounds interesting, do you mean like in the card description?

**Comment by tionis** [comment]
I mean a functionality similar to Trello. When you attach a link (not in the description but via its own field) a bit of metadata for the link is shown on the card.(similar how many chat services show link previews)

This means thumbnails for YouTube and a short text for simple website links. Of you want I could send a picture of what I mean.

**Comment by JordanKnott** [comment]
Please do!

**Comment by tionis** [comment]
Ok, so I was mistaken and thought Trello has this implemented, so I attached a few examples how discord handles this:
![](https://i.imgur.com/ceh0DcT.png)
![](https://i.imgur.com/AnqCuca.png)
