### ISSUE TITLE
Feature Request: More metadata in card

### ISSUE THREAD

**Issue by tionis** [JordanKnott/project-citadel#22]
What do you think about following features?
 - Timelog (Logs who worked on this, when and how long)
 - Importance (As far as I remember that was a huge thing in GANTT?)
 - Dependencies (Unsure how this would be implemented exactly but again useful for GANTT)
 - Assignees (Assign board members to cards)
 - Swimlane (This is more of an UI thing, swimlanes could be triggered with labels or simply saved in the card data)

**Comment by JordanKnott** [comment]
Hi there thanks for the suggestions! 
1. Integrated time tracking is something I plan on adding in the future 
2. I'm not sure about this feature, I'll have to give it some thought (you could do something similar through labels)
3. Dependencies will likely be added when I add the timeline view (a gantt chart with swim lanes)
4. You already can assign members to cards ( I believe the action button when viewing the task details is called "Assignees".
5. This will be implemented in the timeline view, where the lanes are task groups (lists)

**Comment by tionis** [comment]
That sounds awesome and quite thought through!

**Comment by JordanKnott** [comment]
I'm going to go ahead and close this issue!

**Comment by tionis** [comment]
I was just thinking about a few use cases and thought of / remembered following features. What do you think about them?  
 - Map - map a card to a location and show all cards of a board on a map
- Voting/reactions on cards
- card aging - if cards aren't moved for a specific time there is a visual indicator
- list limits - limit amount of cards per list
- nested ToDo lists
- API access over tokens in settings panel

**Comment by JordanKnott** [comment]
1. An interesting idea, perhaps something Ill try to add in the future (though I'm not sure of the use case for it?) 
2. Already planned! 
3. Also planned! 
4. Also, also planned! 
5. Hmm not sure about this one as we have checklists already. What use case did you have in mind for this? 
6. Something I could add in the future (you can also currently get a long lived token through the `citadel` command which is what I use for the graphql playground)
7. Planned!

**Comment by tionis** [comment]
Ok, awesome, now I'm kinda out of ideas.  
The nested todo list idea is perhaps handled good enough with the already existing multiple checklists.

**Comment by tionis** [comment]
Regarding the Map feature: 
Some people(including me) use kanban boards as a better way to organize post it like notes (kinda like google keep).  
You could for example save a few restaurants or other places you like in there and with a button press start navigating there.   
I've also thought about using some custom fields and a location for a simple CRM system, but thats a very special use case.  
The feature may shine best when trying to plan a vacation.
