### ISSUE TITLE
Create issues for features of the roadmap

### ISSUE THREAD

**Issue by alexanderadam** [JordanKnott/project-citadel#3]
IMHO it's better to track issues in a GitHub issue than [a roadmap in the Readme](https://github.com/JordanKnott/project-citadel#roadmap).

**PS:** Citadel looks so great! Just wow!

**Comment by JordanKnott** [comment]
Hmm, you might be right - I'll most likely move them over to issues marked as enhancements. 

That way I can reference them in my commits and PRs. 

Thanks for the suggestion!
