### ISSUE TITLE
Project rename - looking for suggestions!

### ISSUE THREAD

**Issue by JordanKnott** [JordanKnott/project-citadel#8]
In order to avoid confusion with a project that already exists ([citadel](http://www.citadel.org/)), I'm planning on renaming this project.

I currently have a new name in mind but I'm open to any suggestions!

**Comment by LeBaux** [comment]
if you look at other project management tools, boards and other collab software you can virtually pick anything you like. You mentioned on Reddit you just liked the word Citadel. So just look for another cool word you like. If you keep the "project" part, it could be literally whatever. Project Eggplant.

Easy way to make this unique enough for Google is adding some sort of free, libre or open to the name. For example Open Bastila.

**Comment by LeBaux** [comment]
The Eggplant only came to mind because it is purple, just like your prototype. The only downside is people use :eggplant: emoji to say ding dong. But I honestly think it might even be a plus since it is memorable.

But I think there might be more suitable name out there. Curious what you end up with.

**Comment by tionis** [comment]
To give a few more (kind stupid) suggestions for names:
 - Boardify (to go for the -ify name scheme)
 - Kanbany

**Comment by LeBaux** [comment]
Honestly, both OK, but I didn't do any deep research if there isn't tool
named that already. How about Kanbanana? I don't know what is with me and
produce 😂

**Comment by tionis** [comment]
It seems there is already a pip project named Boardify.
What about something completly unrelated like Fenrir, Wotan, Heimdall(I think that ones used),

**Comment by JordanKnott** [comment]
I like fenrir! 

Currently the name I have in mind is Taskcafe, thoughts?

**Comment by tionis** [comment]
I like that! Its professional and interesting.

**Comment by JordanKnott** [comment]
I think I'm gonna go with Taskcafe - the rename will probably happen sometime this weekend.

Thanks for all the suggestions!

**Comment by LoveSponge** [comment]
Just spotted this going through the issues, my 2 cents on taskCafe, I like it, but maybe consider 'taskafe' or 'tascafe'? (Play on words for something like taskify)
Alternatives you may consider;
- Kanbanfection
- DíoModo / ModoDío (corny I know but it rolls of the tongue, bad Spanish for 'godmode')
- Aphrodite (you like the god idea above, how about something to reflect the beauty and clarity this project brings to the table?)
- libreKanban / openKanban
- Claroboard
- MochaTask / Taskspresso / (or some other Italian coffee play on words)
- librespresso (play on words, multiple meanings. Literally 'free quick' - mix of Spanish and Italian)
-  (stay)OnTask / TasKontrol
- CitiGuardar (play on words 'guardar' is Spanish for 'save')
- Kanficiency / OmniKanban
- TaskTower - i don't know now I'm just brainstorming...

I could come up with more but this is all I got for now.

Edit; I realise this is closed but thought it was worth having a few more ideas in the mix. Let me know what you think.

**Comment by JordanKnott** [comment]
Thanks for the suggestions! I like mochatask but I think I'm going to still go with taskcafe.

**Comment by JordanKnott** [comment]
An update: This projected has been renamed with the latest commit!
