### ISSUE TITLE
Docker-Compose Fails to Build

### ISSUE THREAD

**Issue by ngetchell** [JordanKnott/project-citadel#9]
The error is listed below. 

``` 
internal/commands/migrate.go:13:2: module github.com/jordanknott/project-citadel@latest found (v0.0.0-20200719211037-c3b183758960), but does not contain package github.com/jordanknott/project-citadel/api/internal/migrations
Error: running "go build -o dist/citadel cmd/citadel/main.go" failed with exit code 1
exit status 1
````

On Ubuntu 20.04
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build eefe0d31

I'm interested in trying this out so let me know when it works.

**Comment by JordanKnott** [comment]
I didn't add the migration gen the Dockerfile how this is now fixed in the latest commit!
